// Trip data — edit this file to update bookings, todos, and daily plans



export const DAILY_PLAN = [
  {
    leg: "Tokyo", icon: "🗼", dates: "2–6 Jul", nights: 4,
    accommodation: "Shinjuku Airbnb · HM8YXW3WHS · Self check-in · Check-in after 16:00 · Checkout by 11:00",
    days: [
      { day: "Day 1", date: "Thu 2 Jul", title: "Arrival", items: [
        { time: "17:40", activity: "Land Narita — JQ9", type: "locked", note: "Ref ETZ49I" },
        { time: "~19:00", activity: "Narita Express (N'EX) to Shinjuku", type: "locked", note: "~90 mins · ¥3,330 per person · Car 8 Seat 7B · Departs 19:53 arrives 21:13 · Tickets already purchased" },
        { time: "~21:15", activity: "Arrive Shinjuku Station — walk or short taxi to Airbnb", type: "todo", note: "~15 min walk from Shinjuku Station · Look for 平禄寿司 (Sushi restaurant) as landmark · Turn into that alley, building on right" },
        { time: "~21:30", activity: "Check in — Okubo Naoshi Building, Room 402", type: "locked", note: "Building entry: press 呼出 button then 1234 · Room key box code: 4292 · Slippers on, no shoes inside · Ventilation fans OFF (hold 5 sec until green light off) · WiFi: 2G58208A3E5144 · PW: 8xbu5ja6" },
        { time: "~22:00", activity: "Dinner — convenience store or nearby ramen", type: "suggested", note: "7-Eleven, FamilyMart, Lawson all within 2 mins · Ichiran ramen nearby for first proper Japan bowl · Keep it simple — big day tomorrow" },
        { time: "Late", activity: "Early night — long travel day, rest up", type: "suggested" },
      ]},
      { day: "Day 2", date: "Fri 3 Jul", title: "teamLab Borderless + Yanaka + Golden Gai", items: [
        { time: "7:00am", activity: "Eight Coffee Shinjuku — first Tokyo coffee", type: "agreed", note: "Closest specialty coffee to the Airbnb · Opens 7am · Get your bearings over a good flat white before the day starts" },
        { time: "8:00am", activity: "Depart for Roppongi — Oedo or Toei subway line", type: "todo", note: "~20 mins from Shinjuku · Arrive Azabudai Hills with a few minutes to spare" },
        { time: "8:30am", activity: "teamLab Borderless — Azabudai Hills, Roppongi", type: "locked", note: "Ref BSR181944 · Non-refundable · Allow 2.5-3 hrs · Wear socks — some areas require shoes off · No map, no path — wander and get lost intentionally · Key rooms: Forest of Resonating Lamps, Universe of Water Particles, Athletics Forest, Flutter of Butterflies, Resonating Microcosms · En Tea House inside — flowers bloom in your cup, worth the small extra cost · Best photos when you put the phone down and just experience it first" },
        { time: "11:30am", activity: "Leave Roppongi — Hibiya Line to Nippori or Nishi-Nippori", type: "todo", note: "~25 mins · Yanaka is a 5-10 min walk from either station" },
        { time: "12:00pm", activity: "Yanaka Ginza — lunch and wander", type: "agreed", note: "170m covered shopping street · Old Tokyo preserved · Eat standing at the street stalls: menchi katsu (deep fried minced meat cutlet) hot from the fryer, croquettes, ningyo-yaki sweet cakes · Very cheap, very local" },
        { time: "1:00pm", activity: "Yanaka backstreets — laneways, temples, cats", type: "agreed", note: "Yanaka Cemetery — beautiful and peaceful, famous Japanese buried here, lined with old cherry blossom trees · Semi-wild cats roam freely, locals feed them · Dozens of small Buddhist temples tucked between houses · Hagiso arts cafe — old house converted, good for a coffee stop · Just walk slowly and look at the wooden architecture — you are seeing Tokyo that barely exists anymore · Note: had 7-Eleven for lunch today — convenient but not great. Lesson learned — always find a proper spot." },
        { time: "1:30pm", activity: "Shibuya — shopping and explore", type: "agreed", note: "Train from Yanaka to Shibuya · Shibuya Hikarie, Shibuya 109, or just wander the streets · Daikanyama nearby if you want something quieter and more upscale" },
        { time: "Evening", activity: "Dinner in Shibuya — stay local", type: "agreed", note: "Gyukatsu Motomura: beef katsu specialist, always a queue but fast-moving · Afuri Ramen: yuzu-based broth, light and distinctive · Or wander Shibuya back streets — lots of small izakayas and ramen shops away from the tourist strip" },
        { time: "8:00pm", activity: "Golden Gai — bar hop through Tokyo's most unique drinking district", type: "agreed", note: "~200 tiny bars in 6 narrow alleys · Each bar holds 5-8 people max · Cover charge 500-1,000 yen pp, often includes a snack — pay it without fuss · Walk the alleys first before committing · Look for bars with English signs or a welcoming owner making eye contact · Cash only in most places · Move between 2-3 bars over the night — that is the point · Keep quiet after 10pm when you get back to the Airbnb · Last train from Shinjuku ~12:30am · After that: short taxi home" },
      ]},
      { day: "Day 3", date: "Sat 4 Jul", title: "Leaves Coffee + Tsukiji Market", items: [
        { time: "Morning", activity: "Leaves Coffee Roasters — Asakusa/Kuramae area", type: "agreed", note: "One of Tokyo's best specialty roasters · Worth the trip across town · Kuramae is a cool neighbourhood to walk through — Tokyo's Brooklyn, full of craft shops and small studios" },
        { time: "Mid-morning", activity: "Tsukiji Outer Market — wander and graze", type: "agreed", note: "The inner wholesale fish market moved to Toyosu but the outer market stays · Hundreds of food stalls, knife shops, tea shops, pickle vendors · Graze as you walk — tamagoyaki (sweet egg rolls), fresh scallops on the grill, sea urchin, pickled everything · Very crowded on weekends, arrive with patience · This is not a sit-down meal situation, it is a walking eating experience" },
        { time: "Lunch", activity: "Sushi or seafood bowl at Tsukiji — eat it properly", type: "agreed", note: "Several small sushi counters and donburi (rice bowl) spots inside the outer market · Expect to queue briefly — worth it · Fresh tuna, salmon, sea urchin at prices you will not find elsewhere · This is the real version of what tourist Japan markets try to replicate" },
        { time: "Early afternoon", activity: "Flexible — choose your afternoon", type: "suggested", note: "Akihabara (electronics and anime, 15 mins from Tsukiji): overwhelming, fascinating, go without buying anything and just absorb it · Ueno Park and museums: big open park, Tokyo National Museum inside, good if you want calm after the market · Asakusa: Senso-ji Temple, the oldest temple in Tokyo, dramatic gate (Kaminarimon) · Harajuku Takeshita Street: teenage fashion, crepes, wild street style · Pick whichever energy matches how you are feeling after Tsukiji" },
        { time: "Evening", activity: "Dinner — your area of choice", type: "suggested", note: "If you ended up in Asakusa: Nakamise street food then yakitori in the backstreets · If Harajuku: Omotesando for a nicer dinner, design-forward neighbourhood · If back near Shinjuku: Shinjuku Kabukicho ramen alleys are excellent" },
      ]},
      { day: "Day 4", date: "Sun 5 Jul", title: "Shibuya + Go-karts", items: [
        { time: "Morning", activity: "Coffee and slow start — pick your cafe", type: "agreed", note: "Fuglen Tokyo in Tomigaya (near Shibuya) opens 8am weekends · Or Eight or Leaves again if you have a favourite by now · Tokyo specialty coffee is genuinely world class — enjoy it" },
        { time: "Late morning", activity: "Shibuya neighbourhood — explore before the crossing", type: "suggested", note: "Daikanyama: upmarket quiet village feel, excellent bookshop (Daikanyama T-Site), good cafes · Nakameguro canal walk if the weather is good · Both are 10-15 mins walk from Shibuya Station" },
        { time: "Lunch", activity: "Shibuya or Harajuku area — your choice", type: "suggested", note: "Gyukatsu Motomura: beef katsu specialist, always a queue but moves fast, excellent · Afuri Ramen Harajuku: yuzu-based broth, light and distinctive, different from the heavy tonkotsu you have probably had · Or just explore and pick something that looks good" },
        { time: "Afternoon", activity: "Shibuya Scramble Crossing — Leah's photo", type: "agreed", note: "Go to Starbucks on the second floor of the building opposite the crossing for the elevated view · Or stand in the crossing itself and just let it wash over you · Best photos mid-afternoon when light is good and the crossing is full · The crossing is only special when you are actually in it — do both" },
        { time: "Late afternoon", activity: "Explore or rest before go-karts", type: "suggested", note: "Meiji Shrine is 15 mins walk from Shibuya — vast forested shrine in the middle of the city · Harajuku Takeshita Street if you have not done it · Back to Shinjuku to rest and get ready" },
        { time: "18:00", activity: "Head to Tokyo Bay — Street Kart shop", type: "todo", note: "Allow time to get there before 19:00 start · IDP required — have it on you · Pay on the night · Full motorcycle helmet and racing suit provided" },
        { time: "19:00", activity: "Street Kart Tokyo Bay — Flagship 2hr go-kart tour", type: "locked", note: "Ref 1413786433 · Viator · 2 adults · ~2hrs on Tokyo streets in a go-kart wearing a costume · One of the most uniquely Tokyo experiences you will have · Take photos at the start before you are too focused on driving" },
        { time: "~21:30", activity: "Dinner after go-karts — Tokyo Bay or head back to Shinjuku", type: "suggested" },
      ]},
      { day: "Day 5", date: "Mon 6 Jul", title: "Depart for Hakone", items: [
        { time: "Morning", activity: "Glitch Cafe — last Tokyo coffee in Shinjuku", type: "agreed", note: "One of Shinjuku's best specialty coffee spots · Good farewell to Tokyo before heading into the mountains" },
        { time: "8:30am", activity: "Check out Shinjuku Airbnb — bags straight to Shinjuku Station", type: "todo", note: "Not returning to Tokyo so no coin locker needed · Remember: ventilation fans OFF before leaving · Key back in the box (code 4292) · Sort rubbish into bins in the room" },
        { time: "9:20am", activity: "Romancecar Hakone 71 — Shinjuku to Hakone-Yumoto", type: "locked", note: "Ref XBZ479551 · Car 4 · Seat 14A (Andrew) + 14B (Leah) · Show confirmation email + Freepass to board · 1hr 35 mins · Panoramic windows · Observation lounge at front of train · Enjoy the scenery — you are heading into the mountains" },
      ]},
    ],
  },
  {
    leg: "Hakone", icon: "🏔️", dates: "6–8 Jul", nights: 2,
    accommodation: "Centurion Hakone Bettei · Ref 5191517143 · PAID IN FULL ¥112,000 · Sukiyaki dinner + breakfast incl · Open-air bath · Tatami floors",
    days: [
      { day: "Day 5 cont.", date: "Mon 6 Jul", title: "Arrive Hakone", items: [
        { time: "10:55am", activity: "Arrive Hakone-Yumoto Station", type: "locked", note: "End of the Romancecar line · Ryokan shuttle available from the station — contact Centurion Hakone Bettei to confirm pickup · Alternatively Hakone Tozan Bus (covered by Freepass) to Sengokuhara area ~40 mins" },
        { time: "11:30am", activity: "Drop bags at Centurion Hakone Bettei — hold until check-in", type: "locked", note: "Confirmed with property · Explore Hakone until 15:00 check-in time · Bags safe with the ryokan" },
        { time: "12:00pm", activity: "Hakone Open Air Museum", type: "locked", note: "Covered by Freepass · One of Japan's most famous outdoor sculpture parks · Picasso pavilion, Henry Moore works, Venetian glass museum inside · Set against mountain backdrop · Allow 2 hours · Cafe on site for lunch" },
        { time: "15:00", activity: "Check in Centurion Hakone Bettei", type: "locked", note: "Ref 5191517143 · PIN 8888 · Paid in full · Tatami floors — shoes off at entrance · Yukata (cotton robe) provided, wear it for dinner and in the ryokan · This is a full traditional ryokan experience — let yourself slow down completely" },
        { time: "Evening", activity: "Sukiyaki dinner at the ryokan — included", type: "locked", note: "Sukiyaki is thin-sliced beef cooked at the table in a sweet soy broth · Dip the cooked beef in raw egg · Vegetables and tofu cooked alongside · Slow, ritualistic, beautiful · Do not rush it" },
        { time: "Night", activity: "Private open-air bath (rotenburo)", type: "suggested", note: "Your room has its own outdoor onsen bath · Hot mineral water, outdoor air, mountain silence · Use it before bed and again in the morning · This is one of the best things about staying at a ryokan · Take your time" },
      ]},
      { day: "Day 6", date: "Tue 7 Jul", title: "Lake Ashi + Owakudani", items: [
        { time: "Morning", activity: "Breakfast at Centurion Hakone Bettei — included", type: "locked", note: "Traditional Japanese breakfast: rice, miso soup, grilled fish, pickles, tofu, egg · Eat slowly, this is part of the ryokan experience · No rushing" },
        { time: "Mid-morning", activity: "Lake Ashi cruise — Togendai or Hakone-machi pier", type: "locked", note: "Covered by Freepass · Pirate-style sightseeing boat across the lake · On a clear day: Mt Fuji directly behind the famous torii gate emerging from the water · July can be misty — beautiful even without Fuji · ~30-40 mins crossing" },
        { time: "Early afternoon", activity: "Owakudani volcanic valley", type: "suggested", note: "Active volcanic area with steam vents and sulphurous pools · Black eggs (kuro-tamago) boiled in the volcanic springs — legend says eating one adds 7 years to your life · Try one · The landscape is genuinely alien — steam rising from cracked earth, strong sulphur smell, dramatic · Ropeway from Sounzan covered by Freepass" },
        { time: "Late afternoon", activity: "Return to ryokan — onsen and rest", type: "suggested", note: "You have hiked and cruised — let the evening be slow · Open-air bath again before dinner · Hakone has a rhythm of its own: nature, onsen, food, sleep. Let it work." },
        { time: "Dinner", activity: "Sukiyaki dinner at the ryokan — included", type: "locked", note: "Second night of sukiyaki · Same ritual, you will appreciate it even more the second time" },
        { time: "Night", activity: "Private onsen — last night in the ryokan", type: "suggested", note: "Make the most of it · Ryokan onsen experiences are one of the things people remember most about Japan" },
      ]},
      { day: "Day 7", date: "Wed 8 Jul", title: "Depart for Kyoto", items: [
        { time: "Morning", activity: "Breakfast at Centurion Hakone Bettei — included", type: "locked", note: "Last ryokan breakfast · Same beautiful Japanese spread · Eat on the tatami, appreciate the quiet before the journey" },
        { time: "11:00am", activity: "Check out by 11:00", type: "todo", note: "Leave room tidy · Return yukata if you took it · Nothing owed — paid in full" },
        { time: "Late morning", activity: "Local train Hakone-Yumoto to Odawara", type: "todo", note: "~15 mins · 310 yen per person · Pay with Suica · Odawara is the Shinkansen connection point" },
        { time: "Midday", activity: "Shinkansen Hikari Odawara to Kyoto", type: "todo", note: "~$234 for two · Buy at the green Shinkansen ticket windows at Odawara Station · Hikari is the semi-express — stops at Odawara, Nagoya, Kyoto · About 2 hours · Watch the landscape change from coast to inland mountains · Mt Fuji visible on the right side heading west on a clear day · Lunch from a station bento (ekiben) or convenience store on the platform" },
      ]},
    ],
  },
  {
    leg: "Kyoto", icon: "⛩️", dates: "8–10 Jul", nights: 2,
    accommodation: "Nohga Hotel Kiyomizu Kyoto · Ref RXS539474 · Double Room, queen bed · PAID via Expedia · Breakfast included · Near Gion/Kiyomizu-dera",
    days: [
      { day: "Day 7 cont.", date: "Wed 8 Jul", title: "Arrive Kyoto", items: [
        { time: "Afternoon", activity: "Arrive Kyoto — check in Nohga Hotel", type: "locked", note: "Ref RXS539474 · Check-in from 15:00 · No after-hours check-in — front desk greets you · Bring passports — Japanese law requires photocopy at check-in for international guests · Checkout by 12:00 · Breakfast included" },
        { time: "Late afternoon", activity: "Gion at dusk — geisha district wander", type: "suggested", note: "Walk Hanamikoji Street as the light goes golden · This is the preserved geisha quarter — wooden machiya townhouses, lanterns, quiet flagstone lanes · Dusk and early evening is the best time: geiko (Kyoto geisha) and maiko (apprentice) may be heading to engagements · Do not photograph them without permission — they are working professionals, not tourist attractions · Just walk slowly and absorb it · Shirakawa canal area nearby — one of the most photogenic streets in Japan at dusk" },
        { time: "Evening", activity: "Dinner in Gion area", type: "suggested", note: "Gion Kappa: casual izakaya, excellent value, very local crowd · Kikunoi Roan: if you want a more refined experience, kaiseki-style but accessible · Or just follow your nose along Shijo Street — dozens of options at every price point · Tofu cuisine is a Kyoto specialty — lighter than you expect, beautifully presented" },
      ]},
      { day: "Day 8", date: "Thu 9 Jul", title: "Fushimi Inari at dawn + Arashiyama Bike Tour", items: [
        { time: "5:00am", activity: "Fushimi Inari — arrive at dawn before the crowds", type: "agreed", note: "Take a taxi from the hotel — ~15 mins, worth the cost at 5am · The 10,000 torii gates glow orange-red in the early light · Almost no other people at this hour · Hike as far up as you want — the full summit takes 2-3 hours, the lower gates are 30-45 mins · The atmosphere at dawn is genuinely spiritual — quiet, still, ancient · Take your time at the lower gates before heading back down" },
        { time: "7:30am", activity: "Return to hotel for breakfast — included", type: "locked", note: "Back by train or taxi · Nohga Hotel breakfast included · Refuel before the afternoon bike tour" },
        { time: "Late morning", activity: "Free time — Kiyomizu-dera temple or Nishiki Market", type: "suggested", note: "Kiyomizu-dera is a 10 min walk from the hotel — wooden stage temple jutting out over a cliff · Nishiki Market (Kyoto's Kitchen): 400m covered arcade of food stalls, pickles, tofu, street snacks · Both are close, both worth it before the afternoon tour" },
        { time: "12:00pm", activity: "Head to Saga-Arashiyama Station for bike tour", type: "todo", note: "JR San-in Line from Kyoto Station to Saga-Arashiyama — ~15 mins · Allow time to arrive before 13:00 start · Meeting point is at the station itself" },
        { time: "1:00pm", activity: "Arashiyama Bike Tour — Bamboo Forest, Monkeys & Hidden Spots", type: "locked", note: "~4 hours guided · English guide · Monkey Park Iwatayama: 20 min hike up to the top, Japanese macaques roam freely, panoramic view of Kyoto · Bamboo Forest Street: the iconic towering bamboo corridor — best experienced moving through it on a bike rather than shuffling with tour groups · Tenryu-ji Temple garden: UNESCO World Heritage, beautiful pond garden with borrowed scenery of the mountains · Togetsukyo Bridge: iconic Arashiyama view, mountain backdrop · Final payment at the start of the tour" },
        { time: "5:00pm", activity: "Tour ends back at Saga-Arashiyama Station", type: "suggested", note: "Train back to central Kyoto" },
        { time: "Evening", activity: "Nishiki Market if not done earlier, then dinner", type: "suggested", note: "Philosopher's Path at dusk if you have energy — canal-side walkway lined with cherry blossom trees · Dinner in Gion or Pontocho: Pontocho is a narrow laneway running parallel to the Kamo River, completely lined with restaurants — one of the most atmospheric dining streets in Japan" },
      ]},
      { day: "Day 9", date: "Fri 10 Jul", title: "Depart for Hiroshima", items: [
        { time: "Morning", activity: "Breakfast at Nohga Hotel — included", type: "locked" },
        { time: "Before 12:00", activity: "Check out — Nohga Hotel Kiyomizu Kyoto", type: "todo", note: "Paid via Expedia · City tax payable at check-out — small amount per person per night · Nothing else owed" },
        { time: "Late morning", activity: "Shinkansen Kyoto to Hiroshima", type: "todo", note: "~$214 for two · Buy at JR ticket windows at Kyoto Station · About 1hr 45 mins on Nozomi (fastest) or 2hrs on Hikari · Sit on the right side heading west for coastal views · Hiroshima Station is the stop — do not continue to Shin-Iwakuni" },
      ]},
    ],
  },
  {
    leg: "Hiroshima", icon: "🕊️", dates: "10–12 Jul", nights: 2,
    accommodation: "Hotel Vista Hiroshima · Ref 5330.082.160 · PIN 2192 · PAID IN FULL ¥32,632 · Near Peace Memorial Park (~21 min walk)",
    days: [
      { day: "Day 9 cont.", date: "Fri 10 Jul", title: "Arrive Hiroshima", items: [
        { time: "Afternoon", activity: "Arrive Hiroshima — check in Hotel Vista", type: "locked", note: "Ref 5330.082.160 · PIN 2192 · Check-in 15:00-00:00 · Paid in full · 21 min walk to Peace Memorial Park or short tram ride" },
        { time: "Late afternoon", activity: "Peace Memorial Park — first visit at dusk", type: "suggested", note: "Walk to the park in the late afternoon · The Atomic Bomb Dome (Genbaku Dome) at dusk is one of the most powerful sights in Japan — the ruined building preserved exactly as it was · The park itself is quiet and contemplative · Children's Peace Monument: thousands of paper cranes, story of Sadako Sasaki · Flame of Peace: burning since 1964, will not be extinguished until all nuclear weapons are abolished · Come here before the museum so you arrive at the museum tomorrow with context · Spend time here quietly — this is not a tourist attraction, it is a memorial" },
        { time: "Evening", activity: "Oysters for dinner — Hiroshima specialty", type: "agreed", note: "Hiroshima produces 60% of Japan's oysters · Oyster Bar Maboya near the Peace Park: excellent, relaxed, outdoor seating · Or Kanawa: famous floating oyster restaurant on the river — book ahead if possible · Various preparations: grilled in shell, deep fried (kaki furai), in hotpot, raw · Hiroshima-style okonomiyaki is the other specialty: layered pancake with noodles inside, very different from Osaka style — try both over the two nights" },
      ]},
      { day: "Day 10", date: "Sat 11 Jul", title: "Peace Museum + Miyajima + Mount Misen hike", items: [
        { time: "8:30am", activity: "Peace Memorial Museum — allow 2-2.5 hours", type: "locked", note: "Opens 8:30am · 200 yen entry · One of the most important museums you will ever visit · Tells the full story of 6 August 1945 through photographs, artefacts, personal testimonies · It is emotionally heavy — that is the point, and it is handled with extraordinary dignity · The watch stopped at 8:15am · The shadow burned into the steps · Take your time and do not rush through it · Exit into the park when you are ready — the river and the trees will be there" },
        { time: "Late morning", activity: "Tram to Hiroshima Port — ferry to Miyajima", type: "agreed", note: "Hiroshima tram from near the museum to Hiroshima Port · JR Ferry or Matsudai ferry across to Miyajima · ~30 min crossing · The island appears as you approach — the floating torii gate of Itsukushima Shrine visible from the water · At high tide the gate appears to float · At low tide you can walk to its base" },
        { time: "Midday", activity: "Itsukushima Shrine and torii gate", type: "agreed", note: "UNESCO World Heritage shrine built over the water · The vermilion buildings reflect in the sea at high tide · Deer wander freely across the island — they are considered sacred messengers · Do not feed them, they will steal your food regardless · Momiji manju: maple-leaf shaped cakes filled with red bean paste, Miyajima specialty — eat several" },
        { time: "Early afternoon", activity: "Lunch before the hike — keep it quick", type: "suggested", note: "Oysters grilled in the shell sold at stalls along the waterfront · Or momiji manju from a bakery · Eat something substantial — the hike is real effort" },
        { time: "Afternoon", activity: "Hike Mount Misen — Daisho-in trail up, ropeway down", type: "agreed", note: "Daisho-in trail: starts at Daisho-in Temple at the base — a stunning complex of stone lanterns, moss-covered Buddhas, prayer wheels · The hike to the summit takes about 90 mins at a steady pace · Dense cedar forest, stone paths, occasional views through the trees · Summit (535m): 360-degree panorama of the Seto Inland Sea, dozens of islands visible, Hiroshima city in the distance · Eternal flame burning since Kobo Daishi lit it 1,200 years ago · Ropeway down from near the summit — covered by separate ticket, worth taking on tired legs · Allow 3 hours including the descent" },
        { time: "Evening", activity: "Ferry back to Hiroshima — oysters for dinner", type: "agreed", note: "Last ferry back is around 17:30-18:00, check schedule · Dinner back in Hiroshima: second round of oysters, or Hiroshima-style okonomiyaki tonight if you had oysters last night · Mitachan is the famous okonomiyaki institution — queue is worth it" },
      ]},
      { day: "Day 11", date: "Sun 12 Jul", title: "Depart for Osaka", items: [
        { time: "Morning", activity: "Check out by 11:00 — Hotel Vista Hiroshima", type: "todo", note: "Paid in full — nothing owed at checkout · Last look at Hiroshima · The city is remarkable for being so alive and vibrant given its history — that is the point it makes" },
        { time: "Late morning", activity: "Shinkansen Hiroshima to Shin-Osaka", type: "todo", note: "~$197 for two · Buy at JR ticket windows at Hiroshima Station · About 1hr 25 mins on Nozomi · Shin-Osaka is the terminus — connect to Osaka city centre on the subway or JR Osaka Loop Line" },
      ]},
    ],
  },
  {
    leg: "Osaka", icon: "🏙️", dates: "12–14 Jul", nights: 2,
    accommodation: "Shizutetsu Hotel Prezio Osaka Shinsaibashi · Ref 6091.751.149 · PIN 7186 · Near Shinsaibashisuji/Namba · No prepayment — pay at property",
    days: [
      { day: "Day 11 cont.", date: "Sun 12 Jul", title: "Arrive Osaka", items: [
        { time: "Afternoon", activity: "Arrive Osaka — check in Shizutetsu Hotel Prezio", type: "locked", note: "Ref 6091.751.149 · PIN 7186 · Check-in 15:00-00:00 · No prepayment — pay 20,028 yen on checkout · Near Shinsaibashisuji shopping arcade and Namba" },
        { time: "Evening", activity: "Dotonbori — first night impression", type: "suggested", note: "5 min walk from the hotel · The neon canal strip that defines Osaka nightlife · Glico Running Man sign · Giant mechanical crab on the Kani Doraku restaurant · Takoyaki (octopus balls): Osaka's signature street food, eaten standing · Okonomiyaki: savoury pancake, Osaka-style is mixed not layered, delicious · Eat your way along the canal · It is loud, bright, and completely overwhelming in the best way" },
        { time: "Night", activity: "Kuromon Ichiba Market or Hozenji Yokocho", type: "suggested", note: "Kuromon: Osaka's kitchen market, open late, seafood and street food · Hozenji Yokocho: tiny moss-covered lane with a small water-throwing temple, restaurants on both sides, deeply atmospheric · Both are 10-15 mins walk from the hotel" },
      ]},
      { day: "Day 12", date: "Mon 13 Jul", title: "Osaka full day", items: [
        { time: "Morning", activity: "Osaka Castle — arrive early to beat the crowds", type: "suggested", note: "Opens 9am · 600 yen entry · The castle itself is a 1930s concrete reconstruction but the stone walls and moat are original and magnificent · Top floor observation deck: panoramic city view · The grounds (Nishinomaru Garden) are large and beautiful · Allow 2 hours including the grounds" },
        { time: "Lunch", activity: "Shinsekai — retro neighbourhood, kushikatsu", type: "suggested", note: "10 mins south of Osaka Castle by subway · Old working-class neighbourhood that time forgot · Tsutenkaku Tower in the centre — dated and wonderful · Kushikatsu: deep-fried skewers of meat and vegetables dipped in sauce — the golden rule is NO DOUBLE DIPPING in the shared sauce · Everything is on skewers: pork, shrimp, quail egg, lotus root, cheese · Very cheap, very filling, very Osaka · Wash it down with Asahi or Sapporo" },
        { time: "Afternoon", activity: "Namba and Amerika-Mura — shopping and culture", type: "suggested", note: "Amerika-Mura (America Village): Osaka's youth culture hub, vintage clothes, street art, young Osakans hanging out · Den Den Town: Osaka's version of Akihabara — electronics and anime, more manageable than Tokyo's version · Shinsaibashisuji: covered shopping arcade running 600m directly from your hotel — everything from department stores to street fashion · Dotonbori canal walk in daylight to see the details you missed last night" },
        { time: "Evening", activity: "Final Japan dinner — make it count", type: "suggested", note: "Osaka is Japan's food capital — this is the last Japanese dinner before the Philippines · Options: return to Dotonbori for one last round of street food · Mizuno on Dotonbori: famous okonomiyaki restaurant, always a queue, worth it · Kani Doraku: the famous crab restaurant with the giant mechanical crab outside · Or just wander and pick somewhere that calls to you · Osaka rewards improvisation over planning when it comes to food" },
      ]},
      { day: "Day 13", date: "Tue 14 Jul", title: "Depart Osaka to Philippines", items: [
        { time: "Morning", activity: "Check out by 11:00 — Shizutetsu Hotel Prezio", type: "todo", note: "Pay 20,028 yen at the front desk · Wise card works here · Store bags at the hotel if needed while you explore before heading to KIX" },
        { time: "Afternoon", activity: "Head to KIX Airport — Haruka Express from Namba", type: "todo", note: "Haruka Express from Namba Station · ~75 mins to KIX · ~2,000 yen per person · Check Suica balance first · Buy Haruka ticket at the station if Suica does not cover it · Allow plenty of time — international check-in closes 60 mins before departure" },
        { time: "22:25", activity: "Fly KIX to MNL — GK81 Jetstar Japan", type: "locked", note: "Ref EN62XK · Arrive MNL 01:50 · Late night flight — sleep on the plane · You have been in Japan for 13 days · Philippines starts tomorrow morning" },
      ]},
    ],
  },
  {
    leg: "Boracay", icon: "🏖️", dates: "15–21 Jul", nights: 6,
    accommodation: "Henann Regency Resort & Spa · Ref QA62J4ANR · Station 2 White Beach · Breakfast included",
    days: [
      { day: "Day 14", date: "Wed 15 Jul", title: "Arrive Boracay", items: [
        { time: "7:05am", activity: "Fly MNL to Caticlan — Z2213", type: "locked", note: "Ref BE19VW · Arrive 08:10 · Terminal 2 departure · Short domestic hop · You have been awake since landing at 1:50am — the beach will fix everything" },
        { time: "8:30am", activity: "Boat Caticlan to Boracay — ~10 mins", type: "suggested", note: "Tricycle or shuttle from Caticlan Airport to the ferry terminal · Ferry is 10 mins across the channel · Small boat, bags get wet sometimes — keep electronics in a dry bag · Pay environmental fee and tourism fee at the terminal — about 200-300 PHP total per person · Confirmation ref QA62J4ANR · Pay on arrival" },
        { time: "9:30am", activity: "Arrive White Beach — beach by 9:30am", type: "suggested", note: "Henann Regency is Station 2 — central White Beach · Check-in not until 15:00 but they will hold bags · Ask about early check-in — sometimes available for a fee or if room is ready · White Beach is 4km of powdery white sand and calm turquoise water · This is the reward for 13 days of trains and temples — put your feet in the sand immediately" },
        { time: "15:00", activity: "Check in Henann Regency Resort & Spa", type: "todo", note: "Ref QA62J4ANR · Bed type: confirmed double/queen requested · Breakfast included daily · Henann group access — all 5 Henann properties including Station 1 beachfront · 3 pools on site · 6 restaurants" },
        { time: "Evening", activity: "First resort dinner — celebrate arriving", type: "suggested", note: "6 restaurants to choose from at the resort · Or walk the beachfront path for sunset drinks · D'Talipapa seafood market near Station 2: pick your fresh seafood and they cook it to order · First proper sleep in an actual bed after a long travel day" },
      ]},
      { day: "Days 15-20", date: "Thu 16 – Mon 20 Jul", title: "Boracay — 5 full beach days", items: [
        { time: "Daily", activity: "Breakfast buffet — Henann Regency, included", type: "locked", note: "Large buffet · Start each day well · No rush — this is the holiday portion of the holiday" },
        { time: "All day", activity: "White Beach — swim, relax, explore", type: "suggested", note: "Station 2 is the most beautiful section of White Beach · The water is calm inside the reef — safe swimming, perfect for snorkelling · Walk the full 4km beach at least once · Watch the sunset from Willy's Rock (the famous rock with the shrine) · Early morning is magical — almost empty, the light is extraordinary" },
        { time: "Activities", activity: "Watersports and island activities — as you feel like it", type: "suggested", note: "Henann group access covers all 5 Henann properties including Station 1 (the most premium beachfront) · Island hopping: half-day boat tour around the smaller surrounding islands, snorkelling included — book at any beachside tour operator, ~1,500-2,000 PHP per person · Cliff diving at Ariel's Point: full-day boat trip with cliffs at various heights, popular, book ahead · Paraw sailing: traditional outrigger sailboat, sunset cruise is the classic version · Helmet diving: walk on the seabed wearing a diving helmet — no certification needed, surreal experience" },
        { time: "Evenings", activity: "Beachfront bars and restaurants", type: "suggested", note: "Nigi Nigi Nu Noos: beloved beachfront bar and restaurant, cold San Miguel, excellent food, right on the water · Station 3 at dusk: quieter end of the beach, more local feel · Jonah's Fruit Shake: famous smoothie stand, open from morning, the mango shake is legendary · The party bars are at Station 1/2 border if you want that · But after 13 days of Japan, you might just want your feet in the sand with a cold beer" },
      ]},
      { day: "Day 21", date: "Tue 21 Jul", title: "Depart Boracay", items: [
        { time: "12:00", activity: "Check out Henann Regency", type: "todo", note: "Last beach morning · Breakfast included until check-out · Take photos · The White Beach at morning is one of the most beautiful places you will have been" },
        { time: "15:45", activity: "Fly Caticlan to MNL — Z2224", type: "locked", note: "Ref BE19VW · Arrive MNL 16:50 · Ferry to Caticlan then short hop to Manila · Allow extra time for the ferry — tides and boat schedules can delay" },
        { time: "17:30", activity: "Check in Belmont Hotel Manila", type: "todo", note: "Ref QA39ZC2AJ · Check-in from 14:00 · Check-in location: Meeting Room (not the lobby) · Watch for check-in email 24hrs prior with exact instructions · Terminal 3 adjacent — 5 min walk to your departure terminal tomorrow night · Standard Queen · Breakfast included" },
        { time: "Evening", activity: "Dinner near Belmont / Terminal 3", type: "suggested", note: "Resorts World Manila is a 10 min taxi from Belmont — large complex with restaurants, casino, entertainment · Or keep it simple near the airport: early night, pack properly, get ready for the long haul home" },
      ]},
    ],
  },
  {
    leg: "Manila Home", icon: "✈️", dates: "22–23 Jul", nights: 0,
    accommodation: "Belmont Hotel Manila · Ref QA39ZC2AJ · Terminal 3 adjacent · Breakfast included",
    days: [
      { day: "Day 22", date: "Wed 22 Jul", title: "Fly home", items: [
        { time: "Morning", activity: "Breakfast at Belmont Hotel — included", type: "locked", note: "Last morning · 21 nights done · Eat well before the long flight home" },
        { time: "12:00", activity: "Check out Belmont Hotel", type: "todo", note: "Nothing owed — paid · Ask hotel to hold bags if you want to explore before check-in · Or head straight to the terminal — it is a 5 min walk" },
        { time: "Afternoon", activity: "Terminal 3 — check in for PR211", type: "todo", note: "Philippine Airlines check-in opens 3 hours before departure · International check-in closes 60 mins before · Terminal 3 is modern and comfortable · Duty free shopping if you want last-minute gifts" },
        { time: "21:35", activity: "Fly MNL to SYD — PR211 Philippine Airlines", type: "locked", note: "Ref DIB090 · Arrive SYD 08:00 Thu 23 Jul · ~8 hour flight · Sleep if you can · You have seen Japan from end to end and spent a week on one of the world's most beautiful beaches · Welcome home" },
      ]},
    ],
  },
];

export const TRIP_DATA = {
  meta: { dates: "2 Jul to 23 Jul 2026", travellers: "Andrew Percival & Leah Tredway", qff: "2013874546" },
  bookings: [
    { ref: "ETZ49I", date: "2 Jul", detail: "SYD to BNE to TYO (JQ810 + JQ9 Jetstar)", cost: "$387 + 62k pts", status: "locked" },
    { ref: "EN62XK", date: "14 Jul 22:25", detail: "KIX to MNL (GK81 Jetstar Japan)", cost: "Cash", status: "locked" },
    { ref: "BE19VW", date: "15 Jul 07:05", detail: "MNL to Caticlan (Z2213 AirAsia)", cost: "$439 total", status: "locked" },
    { ref: "BE19VW", date: "21 Jul 15:45", detail: "Caticlan to MNL (Z2224 AirAsia)", cost: "Included", status: "locked" },
    { ref: "DIB090", date: "22 Jul 21:35", detail: "MNL to SYD (PR211 Philippine Airlines)", cost: "80k pts", status: "locked" },
    { ref: "HM8YXW3WHS", date: "2-6 Jul", detail: "Tokyo Airbnb — Shinjuku 4 nights · Host Yumi · Self check-in", cost: "$572.97", status: "locked" },
    { ref: "5191517143", date: "6-8 Jul", detail: "Centurion Hakone Bettei — 2 nights · PAID IN FULL ¥112,000 · PIN 8888 · Sukiyaki dinner + breakfast · Open-air bath", cost: "¥112,000", status: "locked" },
    { ref: "RXS539474", date: "8-10 Jul", detail: "Nohga Hotel Kiyomizu Kyoto — 2 nights · Double Room, queen bed · Breakfast incl · PAID via Expedia", cost: "Paid", status: "locked" },
    { ref: "5330.082.160", date: "10-12 Jul", detail: "Hotel Vista Hiroshima — 2 nights · Moderate Double Room · PIN 2192 · PAID IN FULL", cost: "¥32,632", status: "locked" },
    { ref: "6091.751.149", date: "12-14 Jul", detail: "Shizutetsu Hotel Prezio Osaka Shinsaibashi — 2 nights · Double Room · PIN 7186 · No prepayment, pay at property", cost: "¥20,028", status: "locked" },
    { ref: "QA62J4ANR", date: "15-21 Jul", detail: "Henann Regency Boracay — 6 nights · Superior Room · Breakfast incl", cost: "94,807 pts", status: "locked" },
    { ref: "QA39ZC2AJ", date: "21-22 Jul", detail: "Belmont Hotel Manila — 1 night · Standard Queen · Breakfast incl", cost: "$151.05", status: "locked" },
    { ref: "RS-CTM1005685", date: "2-23 Jul", detail: "ReadySet Travel Insurance — Premium Single Trip (Andrew + Leah)", cost: "$155.68", status: "locked" },
    { ref: "BSR181944", date: "3 Jul 08:30", detail: "teamLab Borderless — Azabudai Hills, Roppongi (2 adults)", cost: "$88.70", status: "locked" },
    { ref: "XBZ479551", date: "6 Jul 09:20", detail: "Romancecar Hakone 71 — Shinjuku to Hakone-Yumoto · Car 4 · Seat 14A + 14B", cost: "AUD $22.96", status: "locked" },
    { ref: "ZPS305093", date: "6-8 Jul", detail: "Digital Hakone Freepass 2-day (2 adults) — PAID, shared with Andrew, both activated", cost: "~$126.60", status: "locked" },
    { ref: "1413786433", date: "5 Jul 19:00", detail: "Street Kart Tokyo Bay — Flagship 2hr go-kart tour · 2 adults · Tokyo Bay shop · IDP required", cost: "Viator", status: "locked" },
    { ref: "Viator-Kyoto", date: "9 Jul 13:00", detail: "Afternoon Kyoto Bike Tour — Bamboo Forest, Monkeys & Hidden Spots · 2 adults · 4hrs · Booked by Leah · Final payment due Wednesday", cost: "TBC", status: "locked" },
  ],
  todos: [
    { item: "Kyoto bike tour final payment — due Wednesday", urgency: "low", when: "Wednesday (already scheduled)", cost: "—", notes: "Final payment scheduled for Wednesday — e-ticket will be available after. No action needed, just on track." },
    { item: "Email Henann re: early check-in", urgency: "medium", when: "Closer to 15 Jul, or combine with bed type follow-up", cost: "—", notes: "Arriving ~9am 15 Jul, check-in from 15:00. Ref QA62J4ANR. Still awaiting reply on bed type request too." },
    { item: "Japan SIM / eSIM", urgency: "low", when: "At Narita on arrival", cost: "~$0-50", notes: "2x free eSIMs already from Klook bookings — check these first. Buy backup SIM at Narita only if needed." },
  ],
  gear: [
    { item: "2x Anker PowerBank 20,000mAh", status: "done", cost: "~$139", notes: "Arrived" },
    { item: "ReadySet Travel Insurance — Premium", status: "done", cost: "$155.68", notes: "Policy RS-CTM1005685 · Both names · Japan + Philippines · 2-23 Jul" },
    { item: "teamLab Borderless tickets", status: "done", cost: "$88.70", notes: "BSR181944 · 3 Jul 08:30 · Azabudai Hills · Mobile voucher · Non-refundable" },
    { item: "Patagonia Black Hole Pack 25L — Black", status: "done", cost: "$186.62", notes: "Rushfaster EOFY · #WQ5NV2H85 · Express shipping · Arrives before 2 Jul" },
    { item: "Hoka Clifton 10 (Andrew) — Size 9.5", status: "done", cost: "~$220", notes: "Confirmed great for all legs incl Mount Misen — no further action needed" },
    { item: "Leah's NB 1080s", status: "done", cost: "Owned", notes: "Confirmed great for all legs incl Mount Misen — no further action needed" },
    { item: "Digital Hakone Freepass 2-day", status: "done", cost: "~$127", notes: "ZPS305093 PAID, shared and activated for both Andrew and Leah" },
    { item: "Romancecar Hakone 71", status: "done", cost: "AUD $22.96", notes: "XBZ479551 PAID · Car 4 · Seat 14A (Andrew) + 14B (Leah) · Show confirmation email + Freepass to board" },
    { item: "Centurion Hakone Bettei", status: "done", cost: "¥112,000", notes: "Ref 5191517143 · PIN 8888 · Paid in full · Bags can be dropped on arrival, held until check-in · Ryokan runs shuttle from nearby stations" },
    { item: "Nohga Hotel Kiyomizu Kyoto", status: "done", cost: "Paid", notes: "Ref RXS539474 · Queen bed, breakfast incl · Booked via Expedia · Leah's pick — near Gion/Kiyomizu-dera" },
    { item: "Hotel Vista Hiroshima", status: "done", cost: "¥32,632", notes: "Ref 5330.082.160 · PIN 2192 · PAID IN FULL — nothing owed at checkout" },
    { item: "Shizutetsu Hotel Prezio Osaka", status: "done", cost: "¥20,028", notes: "Ref 6091.751.149 · PIN 7186 · No prepayment — pay at property on checkout" },
    { item: "Street Kart Tokyo Bay — go-karts", status: "done", cost: "Viator", notes: "Ref 1413786433 · 5 Jul 19:00 · 2hr tour · Tokyo Bay shop · IDP required" },
    { item: "Arashiyama Bike Tour (Kyoto)", status: "done", cost: "TBC", notes: "Booked by Leah · 9 Jul 13:00 · Bamboo Forest, Monkey Park Iwatayama, Tenryu-ji garden, Togetsukyo Bridge · Final payment due Wednesday" },
    { item: "Suica — iPhone Wallet (both phones)", status: "done", cost: "—", notes: "Set up early, ready to go" },
    { item: "Wise digital cards (both)", status: "done", cost: "—", notes: "Ready for JPY and PHP — no pre-conversion needed" },
    { item: "Kathmandu — pants, shirts, compression flight socks", status: "done", cost: "~$150-200", notes: "Purchased" },
    { item: "IDP — International Driving Permit", status: "done", cost: "~$35", notes: "Picked up from NRMA · Required for go-karts Tokyo" },
    { item: "Japan SIM / eSIM", status: "todo", cost: "~$0-50", notes: "Check 2x free Klook eSIMs first. Buy at Narita if needed." },
  ],
  transport: [
    { leg: "Narita to Shinjuku", how: "Narita Express (N'EX) · Car 8 Seat 7B · departs 19:53 arrives 21:13", cost: "¥3,330 pp — PAID", book: "Tickets purchased" },
    { leg: "Tokyo local", how: "Suica card (iPhone Wallet)", cost: "Pay as you go", book: "Ready to go — both set up" },
    { leg: "Tokyo to Hakone", how: "Romancecar Hakone 71 · 09:20 · Car 4 · 14A+14B", cost: "AUD $22.96", book: "PAID — ref XBZ479551" },
    { leg: "Hakone local", how: "Digital Hakone Freepass 2-day + ryokan shuttle from station", cost: "~$127", book: "PAID — ref ZPS305093, both activated" },
    { leg: "Hakone-Yumoto to Odawara", how: "Local train", cost: "~$6", book: "Suica" },
    { leg: "Odawara to Kyoto", how: "Shinkansen Hikari", cost: "~$234 (two)", book: "Buy at station · 8 Jul" },
    { leg: "Kyoto local — Day 8", how: "JR San-in Line to Saga-Arashiyama for bike tour", cost: "~$10 (two)", book: "Suica · 9 Jul" },
    { leg: "Kyoto to Hiroshima", how: "Shinkansen", cost: "~$214 (two)", book: "Buy at station · 10 Jul" },
    { leg: "Hiroshima to Miyajima ferry", how: "Tram + JR/Matsudai ferry (~30 min crossing)", cost: "~$15 (two, return)", book: "Pay on the day · 11 Jul" },
    { leg: "Hiroshima to Shin-Osaka", how: "Shinkansen", cost: "~$197 (two)", book: "Buy at station · 12 Jul" },
    { leg: "Osaka local", how: "Suica", cost: "Pay as you go", book: "—" },
    { leg: "Osaka Namba to KIX", how: "Haruka Express (~75 mins)", cost: "~$30", book: "Suica · 14 Jul" },
  ],
  budget: [
    { item: "Flights (paid)", cost: "$826", status: "paid" },
    { item: "Travel Insurance (paid)", cost: "$155.68", status: "paid" },
    { item: "teamLab Borderless (paid)", cost: "$88.70", status: "paid" },
    { item: "Patagonia Backpack (paid)", cost: "$186.62", status: "paid" },
    { item: "Hoka Clifton 10 (paid)", cost: "~$220", status: "paid" },
    { item: "Tokyo Airbnb — 4 nights (paid)", cost: "$572.97", status: "paid" },
    { item: "Centurion Hakone Bettei — 2 nights (paid in full)", cost: "¥112,000", status: "paid" },
    { item: "Nohga Hotel Kiyomizu Kyoto — 2 nights (paid)", cost: "Paid", status: "paid" },
    { item: "Hotel Vista Hiroshima — 2 nights (paid in full)", cost: "¥32,632", status: "paid" },
    { item: "Shizutetsu Hotel Prezio Osaka — 2 nights (pay at property)", cost: "¥20,028", status: "est" },
    { item: "Belmont Hotel Manila (paid)", cost: "$151.05", status: "paid" },
    { item: "Digital Hakone Freepass (paid)", cost: "~$127", status: "paid" },
    { item: "Romancecar Hakone 71 (paid)", cost: "AUD $22.96", status: "paid" },
    { item: "N'EX Narita to Shinjuku (paid)", cost: "¥3,330 pp", status: "paid" },
    { item: "Street Kart Tokyo Bay go-karts (paid)", cost: "Viator", status: "paid" },
    { item: "Arashiyama Bike Tour (Kyoto, final payment Wednesday)", cost: "TBC", status: "est" },
    { item: "Kathmandu clothing (paid)", cost: "~$175", status: "paid" },
    { item: "IDP — NRMA (paid)", cost: "~$35", status: "paid" },
    { item: "Miyajima ferry + Mount Misen ropeway (optional one-way)", cost: "~$50-70 (two)", status: "est" },
    { item: "Japan transport (remaining — Shinkansen legs + Suica)", cost: "~$500", status: "est" },
    { item: "Japan food ~$60/day x 13", cost: "~$780", status: "est" },
    { item: "Philippines food ~$30/day x 7", cost: "~$210", status: "est" },
    { item: "Activities / entrance fees", cost: "~$300", status: "est" },
    { item: "Misc / contingency", cost: "~$300", status: "est" },
  ],
};
