// Trip data — edit this file to update bookings, todos, and daily plans



export const DAILY_PLAN = [
  {
    leg: "Tokyo", icon: "🗼", dates: "2–6 Jul", nights: 4,
    accommodation: "Shinjuku Airbnb · HM8YXW3WHS · Self check-in · Check-in after 16:00 · Checkout by 11:00",
    days: [
      { day: "Day 1", date: "Thu 2 Jul", title: "Arrival", items: [
        { time: "17:40", activity: "Land Narita — JQ9", type: "locked", note: "Ref ETZ49I" },
        { time: "18:00", activity: "Suica ready on iPhone Wallet", type: "locked", note: "Set up early — both phones loaded and ready, no action needed on arrival" },
        { time: "19:30", activity: "Check in to Shinjuku Airbnb — self check-in via key safe", type: "locked", note: "HM8YXW3WHS · 2 Chome-20 Hyakunincho · Host Yumi +81 80-7657-3699 · ID copies + date confirmation sent — fully ready" },
        { time: "20:00", activity: "Dinner near hotel", type: "suggested" },
        { time: "21:30", activity: "Early night — recover from travel", type: "suggested" },
      ]},
      { day: "Day 2", date: "Fri 3 Jul", title: "teamLab + Yanaka + Golden Gai", items: [
        { time: "7:00am", activity: "Fuglen Tokyo or Eight Coffee — Shinjuku area", type: "agreed" },
        { time: "8:30am", activity: "teamLab Borderless — Azabudai Hills, Roppongi", type: "locked", note: "Ref BSR181944 · Non-refundable · ~2.5 hrs" },
        { time: "11:30am", activity: "Train Roppongi to Yanaka (~30 min direct)", type: "agreed" },
        { time: "12:30pm", activity: "Yanaka Ginza — lunch at local street stalls", type: "agreed" },
        { time: "2:00pm", activity: "Yanaka old town wander — laneways, temples, cemetery, cats", type: "agreed" },
        { time: "5:00pm", activity: "Head to Shinjuku — Golden Gai bar hop", type: "agreed" },
        { time: "Evening", activity: "Dinner, explore, drinks — see how the night goes", type: "suggested", note: "Shibuya crossing is locked in for Day 4 daytime" },
      ]},
      { day: "Day 3", date: "Sat 4 Jul", title: "Leaves Coffee + Tsukiji", items: [
        { time: "Morning", activity: "Leaves Coffee Roasters — Asakusa/Kuramae area", type: "agreed" },
        { time: "Mid-morning", activity: "Tsukiji outer market wander", type: "agreed" },
        { time: "Lunch", activity: "Fresh sushi or seafood bowl at Tsukiji", type: "agreed" },
        { time: "Afternoon", activity: "Flexible — Akihabara, Harajuku, Ueno Park or Asakusa temple", type: "suggested" },
        { time: "Evening", activity: "Dinner — area of choice", type: "suggested" },
      ]},
      { day: "Day 4", date: "Sun 5 Jul", title: "Shibuya daytime + go-karts at night", items: [
        { time: "Morning", activity: "Coffee — Fuglen, Eight or Leaves", type: "agreed" },
        { time: "Lunch", activity: "Shibuya or Harajuku area", type: "suggested" },
        { time: "Afternoon", activity: "Shibuya crossing — daytime for Leah's photo", type: "agreed" },
        { time: "Afternoon", activity: "Flexible — explore Harajuku, Ueno or revisit favourite", type: "suggested" },
        { time: "19:00", activity: "Street Kart Tokyo Bay — Flagship 2hr go-kart tour", type: "locked", note: "Ref 1413786433 · Viator · 2 adults · ~2-2.5 hrs · Tokyo Bay shop · IDP required" },
      ]},
      { day: "Day 5", date: "Mon 6 Jul", title: "Depart for Hakone", items: [
        { time: "Morning", activity: "Glitch Café — Shinjuku (last Tokyo coffee)", type: "agreed" },
        { time: "8:30am", activity: "Check out Shinjuku Airbnb — bags straight to platform", type: "todo", note: "No coin locker needed — you're not returning to Tokyo" },
        { time: "9:20am", activity: "Romancecar Hakone 71 — Shinjuku to Hakone-Yumoto (1h 35m)", type: "locked", note: "Ref XBZ479551 · Car 4 · Seat 14A (Andrew) + 14B (Leah) · Show confirmation email + Freepass to board" },
      ]},
    ],
  },
  {
    leg: "Hakone", icon: "🏔️", dates: "6–8 Jul", nights: 2,
    accommodation: "Centurion Hakone Bettei · Ref 5191517143 · PAID IN FULL ¥112,000 · Sukiyaki dinner + breakfast incl · Open-air bath · Tatami floors",
    days: [
      { day: "Day 5 cont.", date: "Mon 6 Jul", title: "Arrive Hakone", items: [
        { time: "10:55am", activity: "Arrive Hakone-Yumoto", type: "locked" },
        { time: "11:30am", activity: "Drop bags at Centurion Hakone Bettei — they'll hold until check-in", type: "locked", note: "Confirmed with property — drop on arrival, return at designated check-in time" },
        { time: "Afternoon", activity: "Hakone Open Air Museum", type: "locked", note: "Covered by Freepass" },
        { time: "15:00", activity: "Check in Centurion Hakone Bettei", type: "locked", note: "Ref 5191517143 · PIN 8888 · Open-air bath in room · Tatami floors · Paid in full" },
        { time: "Dinner", activity: "Sukiyaki dinner at Centurion Hakone Bettei — included", type: "locked" },
        { time: "Night", activity: "Private onsen", type: "suggested" },
      ]},
      { day: "Day 6", date: "Tue 7 Jul", title: "Lake Ashi + Owakudani", items: [
        { time: "Morning", activity: "Breakfast at Centurion Hakone Bettei — included", type: "locked" },
        { time: "Mid-morning", activity: "Lake Ashi cruise", type: "locked", note: "Covered by Freepass" },
        { time: "Afternoon", activity: "Owakudani volcanic valley — black eggs, steam vents", type: "suggested" },
        { time: "Evening", activity: "Head back to ryokan for dinner", type: "suggested" },
        { time: "Dinner", activity: "Sukiyaki dinner at Centurion Hakone Bettei — included", type: "locked" },
        { time: "Night", activity: "Onsen", type: "suggested" },
      ]},
      { day: "Day 7", date: "Wed 8 Jul", title: "Depart for Kyoto", items: [
        { time: "Morning", activity: "Breakfast at Centurion Hakone Bettei — included", type: "locked" },
        { time: "11:00am", activity: "Check out by 11:00", type: "todo" },
        { time: "Late morning", activity: "Local train Hakone-Yumoto to Odawara (~$6, Suica)", type: "todo" },
        { time: "Midday", activity: "Shinkansen Hikari Odawara to Kyoto (~$234 for two, buy at station)", type: "todo" },
      ]},
    ],
  },
  {
    leg: "Kyoto", icon: "⛩️", dates: "8–10 Jul", nights: 2,
    accommodation: "TBC — 2 nights needed",
    days: [
      { day: "Day 7 cont.", date: "Wed 8 Jul", title: "Arrive Kyoto", items: [
        { time: "Afternoon", activity: "Arrive Kyoto — check in", type: "todo" },
        { time: "Late afternoon", activity: "Gion at dusk — geisha district wander", type: "suggested" },
        { time: "Evening", activity: "Dinner in Gion area", type: "suggested" },
      ]},
      { day: "Day 8", date: "Thu 9 Jul", title: "Fushimi Inari + Arashiyama", items: [
        { time: "5:00am", activity: "Fushimi Inari — before the crowds (gates glow at dawn)", type: "agreed" },
        { time: "8:00am", activity: "Breakfast near Fushimi", type: "suggested" },
        { time: "10:00am", activity: "Arashiyama bamboo grove", type: "suggested" },
        { time: "Lunch", activity: "Arashiyama area", type: "suggested" },
        { time: "Afternoon", activity: "Philosopher's Path", type: "suggested" },
        { time: "Evening", activity: "Nishiki Market", type: "suggested" },
      ]},
      { day: "Day 9", date: "Fri 10 Jul", title: "Depart for Hiroshima", items: [
        { time: "Morning", activity: "Check out Kyoto accommodation", type: "todo" },
        { time: "Late morning", activity: "Shinkansen Kyoto to Hiroshima (~$214 for two, buy at station)", type: "todo" },
      ]},
    ],
  },
  {
    leg: "Hiroshima", icon: "🕊️", dates: "10–12 Jul", nights: 2,
    accommodation: "TBC — 2 nights needed",
    days: [
      { day: "Day 9 cont.", date: "Fri 10 Jul", title: "Arrive Hiroshima", items: [
        { time: "Afternoon", activity: "Arrive Hiroshima — check in", type: "todo" },
        { time: "Late afternoon", activity: "Peace Memorial Park — first visit at dusk", type: "suggested" },
        { time: "Evening", activity: "Oysters for dinner — Hiroshima specialty", type: "agreed" },
      ]},
      { day: "Day 10", date: "Sat 11 Jul", title: "Peace Museum + Miyajima", items: [
        { time: "Morning", activity: "Peace Memorial Museum", type: "locked" },
        { time: "Lunch", activity: "Near museum area", type: "suggested" },
        { time: "Afternoon", activity: "Miyajima Island — floating torii gate, deer", type: "suggested" },
        { time: "Evening", activity: "More oysters", type: "agreed" },
      ]},
      { day: "Day 11", date: "Sun 12 Jul", title: "Depart for Osaka", items: [
        { time: "Morning", activity: "Check out Hiroshima", type: "todo" },
        { time: "Late morning", activity: "Shinkansen Hiroshima to Shin-Osaka (~$197 for two, buy at station)", type: "todo" },
      ]},
    ],
  },
  {
    leg: "Osaka", icon: "🏙️", dates: "12–14 Jul", nights: 2,
    accommodation: "TBC — 2 nights needed",
    days: [
      { day: "Day 11 cont.", date: "Sun 12 Jul", title: "Arrive Osaka", items: [
        { time: "Afternoon", activity: "Arrive Osaka — check in", type: "todo" },
        { time: "Evening", activity: "Dotonbori — neon, canal, street food", type: "suggested" },
        { time: "Night", activity: "Kuromon Market, takoyaki, okonomiyaki", type: "suggested" },
      ]},
      { day: "Day 12", date: "Mon 13 Jul", title: "Osaka full day", items: [
        { time: "Morning", activity: "Osaka Castle — arrive early to beat crowds", type: "suggested" },
        { time: "Lunch", activity: "Shinsekai — retro neighbourhood, kushikatsu", type: "suggested" },
        { time: "Afternoon", activity: "Namba, Amerika-Mura or Hozenji Yokocho laneway", type: "suggested" },
        { time: "Evening", activity: "Final Japan dinner — back to Dotonbori or explore", type: "suggested" },
      ]},
      { day: "Day 13", date: "Tue 14 Jul", title: "Depart Osaka to Philippines", items: [
        { time: "Morning", activity: "Check out Osaka accommodation", type: "todo" },
        { time: "Afternoon", activity: "Head to KIX Airport — Haruka Express from Namba ~75 mins", type: "todo", note: "~$30 Suica or buy Haruka ticket" },
        { time: "22:25", activity: "Fly KIX to MNL — GK81 Jetstar Japan", type: "locked", note: "Ref EN62XK · Arrive MNL 01:50" },
      ]},
    ],
  },
  {
    leg: "Boracay", icon: "🏖️", dates: "15–21 Jul", nights: 6,
    accommodation: "Henann Regency Resort & Spa · Ref QA62J4ANR · Station 2 White Beach · Breakfast included",
    days: [
      { day: "Day 14", date: "Wed 15 Jul", title: "Arrive Boracay", items: [
        { time: "7:05am", activity: "Fly MNL to Caticlan — Z2213", type: "locked", note: "Ref BE19VW · Arrive 08:10" },
        { time: "8:30am", activity: "Boat Caticlan to Boracay (~$5, ~10 mins)", type: "suggested", note: "Confirmation printed ✅ QA62J4ANR · Pay on arrival" },
        { time: "9:30am", activity: "Arrive White Beach — beach by 9:30am", type: "suggested" },
        { time: "15:00", activity: "Check in Henann Regency — request early check-in", type: "todo" },
        { time: "Evening", activity: "First dinner at resort — 6 restaurants to choose from", type: "suggested" },
      ]},
      { day: "Days 15-20", date: "Thu 16 – Mon 20 Jul", title: "Boracay — 5 full beach days", items: [
        { time: "Daily", activity: "Breakfast buffet included at Henann Regency", type: "locked" },
        { time: "All day", activity: "White Beach Station 2, 3 pools, watersports", type: "suggested" },
        { time: "All day", activity: "Henann group access — all properties incl Station 1 beachfront", type: "suggested" },
      ]},
      { day: "Day 21", date: "Tue 21 Jul", title: "Depart Boracay", items: [
        { time: "12:00", activity: "Check out Henann Regency", type: "todo" },
        { time: "15:45", activity: "Fly Caticlan to MNL — Z2224", type: "locked", note: "Ref BE19VW · Arrive MNL 16:50" },
        { time: "17:30", activity: "Check in Belmont Hotel Manila", type: "todo", note: "Ref QA39ZC2AJ · Check-in from 14:00 · Watch for check-in email 24hrs prior · Check-in location: Meeting Room" },
        { time: "Evening", activity: "Dinner near Belmont / Terminal 3 area", type: "suggested" },
      ]},
    ],
  },
  {
    leg: "Manila Home", icon: "✈️", dates: "22–23 Jul", nights: 0,
    accommodation: "Belmont Hotel Manila · Ref QA39ZC2AJ · Terminal 3 adjacent · Breakfast included",
    days: [
      { day: "Day 22", date: "Wed 22 Jul", title: "Fly home", items: [
        { time: "Morning", activity: "Breakfast at Belmont Hotel — included", type: "locked" },
        { time: "12:00", activity: "Check out Belmont Hotel", type: "todo" },
        { time: "Afternoon", activity: "Terminal 3 — check in for PR211, airport time", type: "todo" },
        { time: "21:35", activity: "Fly MNL to SYD — PR211 Philippine Airlines", type: "locked", note: "Ref DIB090 · Arrive SYD 08:00 Thu 23 Jul" },
      ]},
    ],
  },
];

export const TRIP_DATA = {
  meta: { dates: "2 Jul to 23 Jul 2026", travellers: "Andrew Percival & Leah Tredway", qff: "2013874546" },
  bookings: [
    { ref: "ETZ49I", date: "2 Jul", detail: "SYD to BNE to TYO (JQ810 + JQ9 Jetstar)", cost: "$387 + 62k pts", status: "locked" },
    { ref: "EN62XK", date: "14 Jul 22:25", detail: "KIX to MNL (GK81 Jetstar Japan)", cost: "Cash", status: "locked" },
    { ref: "BE19VW", date: "15 Jul 07:05", detail: "MNL to Caticlan (Z2213 AirAsia)", cost: "$439 total", status: "locked" },
    { ref: "BE19VW", date: "21 Jul 15:45", detail: "Caticlan to MNL (Z2224 AirAsia)", cost: "Included", status: "locked" },
    { ref: "DIB090", date: "22 Jul 21:35", detail: "MNL to SYD (PR211 Philippine Airlines)", cost: "80k pts", status: "locked" },
    { ref: "HM8YXW3WHS", date: "2-6 Jul", detail: "Tokyo Airbnb — Shinjuku 4 nights · Host Yumi · Self check-in", cost: "$572.97", status: "locked" },
    { ref: "5191517143", date: "6-8 Jul", detail: "Centurion Hakone Bettei — 2 nights · PAID IN FULL ¥112,000 · PIN 8888 · Sukiyaki dinner + breakfast · Open-air bath", cost: "¥112,000", status: "locked" },
    { ref: "QA62J4ANR", date: "15-21 Jul", detail: "Henann Regency Boracay — 6 nights · Superior Room · Breakfast incl", cost: "94,807 pts", status: "locked" },
    { ref: "QA39ZC2AJ", date: "21-22 Jul", detail: "Belmont Hotel Manila — 1 night · Standard Queen · Breakfast incl", cost: "$151.05", status: "locked" },
    { ref: "RS-CTM1005685", date: "2-23 Jul", detail: "ReadySet Travel Insurance — Premium Single Trip (Andrew + Leah)", cost: "$155.68", status: "locked" },
    { ref: "BSR181944", date: "3 Jul 08:30", detail: "teamLab Borderless — Azabudai Hills, Roppongi (2 adults)", cost: "$88.70", status: "locked" },
    { ref: "XBZ479551", date: "6 Jul 09:20", detail: "Romancecar Hakone 71 — Shinjuku to Hakone-Yumoto · Car 4 · Seat 14A + 14B", cost: "AUD $22.96", status: "locked" },
    { ref: "ZPS305093", date: "6-8 Jul", detail: "Digital Hakone Freepass 2-day (2 adults) — Share Adult 2 pass to Leah when Klook unlocks", cost: "~$126.60", status: "locked" },
    { ref: "1413786433", date: "5 Jul 19:00", detail: "Street Kart Tokyo Bay — Flagship 2hr go-kart tour · 2 adults · Tokyo Bay shop · IDP required", cost: "Viator", status: "locked" },
    { ref: "TBC", date: "8-10 Jul", detail: "Kyoto accommodation — 2 nights", cost: "~$280-360", status: "tbc" },
    { ref: "TBC", date: "10-12 Jul", detail: "Hiroshima accommodation — 2 nights", cost: "~$250-350", status: "tbc" },
    { ref: "TBC", date: "12-14 Jul", detail: "Osaka accommodation — 2 nights", cost: "~$250-350", status: "tbc" },
  ],
  todos: [
    { item: "Kyoto accommodation (8-10 Jul)", urgency: "urgent", when: "This week", cost: "~$280-360", notes: "2 nights. July peak season — Gion fills fast. Gion / Higashiyama area recommended." },
    { item: "Hiroshima accommodation (10-12 Jul)", urgency: "urgent", when: "This week", cost: "~$250-350", notes: "2 nights. Walking distance to Peace Park strongly recommended." },
    { item: "Osaka accommodation (12-14 Jul)", urgency: "urgent", when: "This week", cost: "~$250-350", notes: "2 nights. Dotonbori / Namba area. Late checkout useful — KIX flight not until 22:25." },
    { item: "Contact Henann re: bed type", urgency: "high", when: "This week", cost: "—", notes: "Booking shows 2 Twin Beds. Request double/queen. Ph: +63-362886111. Ref QA62J4ANR." },
    { item: "Kathmandu — Flight pants x2", urgency: "high", when: "Before departure", cost: "~$150-200", notes: "Replace jeans. Check rain shells too." },
    { item: "Aldi — Merino tops + underwear", urgency: "high", when: "Before departure", cost: "~$80-100", notes: "3-4 merino tees each + merino boxers. Stock confirmed in store. Sizing runs small." },
    { item: "Email Henann re: early check-in", urgency: "medium", when: "1-2 weeks before 15 Jul", cost: "—", notes: "Arriving ~9am 15 Jul, check-in from 15:00. Ref QA62J4ANR." },
    { item: "Japan SIM / eSIM", urgency: "low", when: "At Narita on arrival", cost: "~$0-50", notes: "2x free eSIMs already from Klook bookings — check these first. Buy backup SIM at Narita only if needed." },
    { item: "Share Hakone Freepass to Leah", urgency: "low", when: "Closer to 6 Jul — Klook unlocks it automatically", cost: "—", notes: "Freepass ref ZPS305093 · Klook locks sharing until closer to the travel date · No action needed yet" },
    { item: "Wear in Hoka Clifton 10s", urgency: "low", when: "Before 2 Jul", cost: "—", notes: "Don't arrive in Japan with new shoes. Wear them now." },
  ],
  gear: [
    { item: "2x Anker PowerBank 20,000mAh", status: "done", cost: "~$139", notes: "Arrived" },
    { item: "ReadySet Travel Insurance — Premium", status: "done", cost: "$155.68", notes: "Policy RS-CTM1005685 · Both names · Japan + Philippines · 2-23 Jul" },
    { item: "teamLab Borderless tickets", status: "done", cost: "$88.70", notes: "BSR181944 · 3 Jul 08:30 · Azabudai Hills · Mobile voucher · Non-refundable" },
    { item: "Patagonia Black Hole Pack 25L — Black", status: "done", cost: "$186.62", notes: "Rushfaster EOFY · #WQ5NV2H85 · Express shipping · Arrives before 2 Jul" },
    { item: "Hoka Clifton 10 (Andrew) — Size 9.5", status: "done", cost: "~$220", notes: "Rebel Sport Maitland · Wear in before 2 Jul" },
    { item: "Leah's NB 1080s", status: "done", cost: "Owned", notes: "Confirmed suitable — no replacement needed" },
    { item: "Digital Hakone Freepass 2-day", status: "done", cost: "~$127", notes: "ZPS305093 PAID · Share to Leah when Klook unlocks closer to 6 Jul" },
    { item: "Romancecar Hakone 71", status: "done", cost: "AUD $22.96", notes: "XBZ479551 PAID · Car 4 · Seat 14A (Andrew) + 14B (Leah) · Show confirmation email + Freepass to board" },
    { item: "Centurion Hakone Bettei", status: "done", cost: "¥112,000", notes: "Ref 5191517143 · PIN 8888 · Paid in full · Bags can be dropped on arrival, held until check-in" },
    { item: "Street Kart Tokyo Bay — go-karts", status: "done", cost: "Viator", notes: "Ref 1413786433 · 5 Jul 19:00 · 2hr tour · Tokyo Bay shop · IDP required — NRMA Monday 29 Jun" },
    { item: "Suica — iPhone Wallet (both phones)", status: "done", cost: "—", notes: "Set up early, ready to go — no need to wait until Narita" },
    { item: "Wise digital cards (both)", status: "done", cost: "—", notes: "Ready for JPY and PHP — no pre-conversion needed" },
    { item: "Kathmandu Flight pants x2", status: "todo", cost: "~$150-200", notes: "Still to purchase. Check rain shells too." },
    { item: "Aldi Merino tops + underwear", status: "todo", cost: "~$80-100", notes: "3-4 tees each + boxers. Stock confirmed. Sizing runs small." },
    { item: "IDP — International Driving Permit", status: "tomorrow", cost: "~$35", notes: "NRMA in person Monday 29 Jun. Required for go-karts Tokyo." },
    { item: "Japan SIM / eSIM", status: "todo", cost: "~$0-50", notes: "Check 2x free Klook eSIMs first. Buy at Narita if needed." },
  ],
  transport: [
    { leg: "Tokyo local", how: "Suica card (iPhone Wallet)", cost: "Pay as you go", book: "Ready to go — both set up" },
    { leg: "Tokyo to Hakone", how: "Romancecar Hakone 71 · 09:20 · Car 4 · 14A+14B", cost: "AUD $22.96", book: "PAID — ref XBZ479551" },
    { leg: "Hakone local", how: "Digital Hakone Freepass 2-day", cost: "~$127", book: "PAID — ref ZPS305093" },
    { leg: "Hakone-Yumoto to Odawara", how: "Local train", cost: "~$6", book: "Suica" },
    { leg: "Odawara to Kyoto", how: "Shinkansen Hikari", cost: "~$234 (two)", book: "Buy at station · 8 Jul" },
    { leg: "Kyoto to Hiroshima", how: "Shinkansen", cost: "~$214 (two)", book: "Buy at station · 10 Jul" },
    { leg: "Hiroshima to Shin-Osaka", how: "Shinkansen", cost: "~$197 (two)", book: "Buy at station · 12 Jul" },
    { leg: "Osaka local", how: "Suica", cost: "Pay as you go", book: "—" },
    { leg: "Osaka Namba to KIX", how: "Haruka Express (~75 mins)", cost: "~$30", book: "Suica · 14 Jul" },
  ],
  budget: [
    { item: "Flights (paid)", cost: "$826", status: "paid" },
    { item: "Travel Insurance (paid)", cost: "$155.68", status: "paid" },
    { item: "teamLab Borderless (paid)", cost: "$88.70", status: "paid" },
    { item: "Patagonia Backpack (paid)", cost: "$186.62", status: "paid" },
    { item: "Hoka Clifton 10 (paid)", cost: "~$220", status: "paid" },
    { item: "Tokyo Airbnb — 4 nights (paid)", cost: "$572.97", status: "paid" },
    { item: "Centurion Hakone Bettei — 2 nights (paid in full)", cost: "¥112,000", status: "paid" },
    { item: "Belmont Hotel Manila (paid)", cost: "$151.05", status: "paid" },
    { item: "Digital Hakone Freepass (paid)", cost: "~$127", status: "paid" },
    { item: "Romancecar Hakone 71 (paid)", cost: "AUD $22.96", status: "paid" },
    { item: "Street Kart Tokyo Bay go-karts (paid)", cost: "Viator", status: "paid" },
    { item: "Kathmandu + Aldi clothing", cost: "~$300", status: "todo" },
    { item: "IDP — NRMA", cost: "~$35", status: "todo" },
    { item: "Kyoto accommodation (2 nights)", cost: "~$280-360", status: "est" },
    { item: "Hiroshima accommodation (2 nights)", cost: "~$250-350", status: "est" },
    { item: "Osaka accommodation (2 nights)", cost: "~$250-350", status: "est" },
    { item: "Japan transport (remaining — Shinkansen legs + Suica)", cost: "~$500", status: "est" },
    { item: "Japan food ~$60/day x 13", cost: "~$780", status: "est" },
    { item: "Philippines food ~$30/day x 7", cost: "~$210", status: "est" },
    { item: "Activities / entrance fees", cost: "~$300", status: "est" },
    { item: "Misc / contingency", cost: "~$300", status: "est" },
  ],
};
